
services:
  db:
    image: postgres
    container_name: test-container
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "card_game"
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
#todo test用のDBコンテナの作成