spring:
  application:
    name: backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url:      jdbc:${DATASOURCE_URL:${LOCAL_DATABASE_URL}}
    username: ${SPRING_DATASOURCE_USERNAME:${LOCAL_DATABASE_USERNAME}}
    password: ${SPRING_DATASOURCE_PASSWORD:${LOCAL_DATABASE_PASSWORD}}
  jpa:
    generate-ddl: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: validate
    show-sql: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  sql:
    init:
      encoding: UTF-8
  web:
    resources:
      static-locations: classpath:/static/
server:
  port: ${PORT:8080}
logging:
  level:
    org.springframework: DEBUG