spring:
  application:
    name: backend
  datasource:
    driver-class-name: org.postgresql.Driver
    # Use the Heroku-provided JDBC URL via SPRING_DATASOURCE_URL
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME:${LOCAL_DATABASE_USERNAME}}
    password: ${DB_PASSWORD:${LOCAL_DATABASE_PASSWORD}}
  jpa:
    generate-ddl: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: validate
    show-sql: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
    password: admin
    user: admin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  sql:
    init:
      encoding: UTF-8
  web:
    resources:
      static-locations: classpath:/static/
server:
  port: ${PORT:8080}