spring:
  application:
    name: backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url:      ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    generate-ddl: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: validate
    show-sql: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
    password: admin
    user: admin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  sql:
    init:
      encoding: UTF-8
  web:
    resources:
      static-locations: classpath:/static/
server:
  port: ${PORT:8080}